apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.env.secret.name }}
type: Opaque
data:
  {{ .Values.image.env.secret.userKey }}: bW9uZ291c2Vy
  {{ .Values.image.env.secret.passwordKey }}: bW9uZ29wYXNzd29yZA==
