apply:
	kubectl apply -f mongo-config.yaml -f mongo-secret.yaml -f mongo-deployment.yaml -f demo-app-deployment.yaml
delete:
	kubectl delete -f mongo-config.yaml -f mongo-secret.yaml -f mongo-deployment.yaml -f demo-app-deployment.yaml
