// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type Pokemon struct {
	ID          int32
	Name        string
	Description string
	Category    string
	Types       []byte
	Abilities   []byte
}
