package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/DeepAung/apiplustech-training/pokedex/database"
	"github.com/DeepAung/apiplustech-training/pokedex/graph/model"
)

// CreatePokemon is the resolver for the createPokemon field.
func (r *mutationResolver) CreatePokemon(ctx context.Context, input model.PokemonInput) (*model.Pokemon, error) {
	types, err := json.Marshal(&input.Types)
	if err != nil {
		return nil, InvalidJsonFieldError("types")
	}

	abilities, err := json.Marshal(&input.Abilities)
	if err != nil {
		return nil, InvalidJsonFieldError("abilities")
	}

	result, err := r.queries.CreatePokemon(ctx, database.CreatePokemonParams{
		Name:        input.Name,
		Description: input.Description,
		Category:    input.Category,
		Types:       string(types),
		Abilities:   string(abilities),
	})
	if err != nil {
		return nil, err
	}

	return r.convertPokemonDBToGraphql(&result)
}

// UpdatePokemon is the resolver for the updatePokemon field.
func (r *mutationResolver) UpdatePokemon(ctx context.Context, id string, input model.PokemonInput) (*model.Pokemon, error) {
	intId, err := strconv.Atoi(id)
	if err != nil {
		return nil, InvalidIntError
	}

	types, err := json.Marshal(&input.Types)
	if err != nil {
		return nil, InvalidJsonFieldError("types")
	}

	abilities, err := json.Marshal(&input.Abilities)
	if err != nil {
		return nil, InvalidJsonFieldError("abilities")
	}

	result, err := r.queries.UpdatePokemon(ctx, database.UpdatePokemonParams{
		Name:        input.Name,
		Description: input.Description,
		Category:    input.Category,
		Types:       string(types),
		Abilities:   string(abilities),
		ID:          int64(intId),
	})
	if err != nil {
		return nil, err
	}

	return r.convertPokemonDBToGraphql(&result)
}

// DeletePokemon is the resolver for the deletePokemon field.
func (r *mutationResolver) DeletePokemon(ctx context.Context, id string) (bool, error) {
	intId, err := strconv.Atoi(id)
	if err != nil {
		return false, InvalidIntError
	}

	err = r.queries.DeletePokemon(ctx, int64(intId))
	return err == nil, err
}

// Pokemons is the resolver for the pokemons field.
func (r *queryResolver) Pokemons(ctx context.Context) ([]*model.Pokemon, error) {
	result, err := r.queries.ListPokemons(ctx)
	if err != nil {
		return nil, err
	}

	pokemons := make([]*model.Pokemon, len(result))
	for i, item := range result {
		pokemons[i], err = r.convertPokemonDBToGraphql(&item)
		if err != nil {
			return nil, err
		}
	}

	return pokemons, nil
}

// PokemonByID is the resolver for the pokemonByID field.
func (r *queryResolver) PokemonByID(ctx context.Context, id string) (*model.Pokemon, error) {
	intId, err := strconv.Atoi(id)
	if err != nil {
		return nil, InvalidIntError
	}

	result, err := r.queries.GetPokemonByID(ctx, int64(intId))
	if err != nil {
		return nil, err
	}

	return r.convertPokemonDBToGraphql(&result)
}

// PokemonByName is the resolver for the pokemonByName field.
func (r *queryResolver) PokemonByName(ctx context.Context, name string) (*model.Pokemon, error) {
	result, err := r.queries.GetPokemonByName(ctx, name)
	if err != nil {
		return nil, err
	}

	return r.convertPokemonDBToGraphql(&result)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
