// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type Pokemon struct {
	ID          int64
	Name        string
	Description string
	Category    string
	Types       string
	Abilities   string
}
